# Generated by Django 4.2.3 on 2023-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_using_gpt_roken_user_using_gpt_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rem_gpt_token",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
