# Generated by Django 4.2.3 on 2023-07-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="data_url",
        ),
        migrations.AddField(
            model_name="audio",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "flac",
                            "amr",
                            "ogg",
                            "webm",
                        ]
                    )
                ],
            ),
        ),
    ]
