# Generated by Django 4.2.3 on 2023-07-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0002_remove_audio_data_url_audio_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="create_at",
        ),
        migrations.AlterField(
            model_name="audio",
            name="modified_script",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="audio",
            name="origin_script",
            field=models.TextField(null=True),
        ),
    ]
