# Generated by Django 4.2.3 on 2023-07-29 05:33

import django.core.validators
from django.db import migrations, models
import scripts.models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0003_remove_audio_create_at_alter_audio_modified_script_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=scripts.models.custom_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "flac",
                            "amr",
                            "ogg",
                            "webm",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="modified_script",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="audio",
            name="origin_script",
            field=models.TextField(default=""),
        ),
    ]
