# Generated by Django 4.2.3 on 2023-07-31 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0004_alter_audio_file_alter_audio_modified_script_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audio",
            old_name="title",
            new_name="script_title",
        ),
    ]
