# Generated by Django 4.2 on 2023-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_rename_title_audio_script_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='summary_script',
            field=models.TextField(default=''),
        ),
    ]
